# Travis YAML file
#
#
# Created by Manmeet Singh, February 2018
# Copyright (c) [2018] Juniper Networks, Inc. All rights reserved.
#
# All rights reserved.
#
# Notice and Disclaimer: This code is licensed to you under the Apache
# License 2.0 (the "License"). You may not use this code except in compliance
# with the License. This code is not an official Juniper product. You can
# obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Third-Party Code: This code may depend on other components under separate
# copyright notice and license terms. Your use of the source code for those
# components is subject to the terms and conditions of the respective license
# as noted in the Third-Party source code file.

language: cpp
sudo: required
dist: xenial
services:
  - docker
compiler:
  - gcc
os:
  - linux
before_install:
  - cd tools/docker; travis_wait docker build -f Dockerfile_p4 -t juniper-p4 .
  - cd ../..
  - docker run -d --name travis-p4 -v `pwd`:/root/JP4Agent --privileged -i -t juniper-p4 /bin/bash
  - docker ps -a
script:
  - docker exec travis-p4 /bin/bash -c "cd /root/JP4Agent/build; ./make-all-null.sh"
  - docker exec travis-p4 /bin/bash -c "cd /root/JP4Agent/test/scripts; ./nullTest.sh"
branches:
only:
  - master
