#
# Regression scripts
# 
# lib.tcl : Common routines
#
# Created by Sandesh Kumar Sodhi, January 2018
# Copyright (c) [2017] Juniper Networks, Inc. All rights reserved.
#
# All rights reserved.
#
# Notice and Disclaimer: This code is licensed to you under the Apache
# License 2.0 (the "License"). You may not use this code except in compliance
# with the License. This code is not an official Juniper product. You can
# obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Third-Party Code: This code may depend on other components under separate
# copyright notice and license terms. Your use of the source code for those
# components is subject to the terms and conditions of the respective license
# as noted in the Third-Party source code file.
#

# apt-get install tdom
package require tdom

match_max 100

#
# prominent log
#
proc log_prominent {str} {
    global script_name
    set now [clock seconds]
    set date [clock format $now -format {%b-%d-%Y %H:%M:%S}]
    puts "\r~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
    puts "\r~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
    puts "\r\[$date\]\[$script_name\] $str"
    puts "\r~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
    puts "\r~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
}

proc log {str} {
    global script_name
    set now [clock seconds]
    set date [clock format $now -format {%b-%d-%Y %H:%M:%S}]
    puts "\r___________\[$date\]\[$script_name\] $str"
}

proc eat_extra_prompts { prompt } {
    #
    # Eat all extra prompts
    #
    set timeout 2
    log "Will eat extra prompts \"$prompt\""
    while 1 {
        expect {
            "$prompt" {
                unset expect_out(buffer)
                log "ate extra prompt \"$prompt\""
            }
            timeout {
                send "\r"
                break
            }
        }
    }
}

