#!/bin/bash
#
# Regression scripts
# 
# start-http-server : Starts http server
#
# Created by Sandesh Kumar Sodhi, January 2018
# Copyright (c) [2017] Juniper Networks, Inc. All rights reserved.
#
# All rights reserved.
#
# Notice and Disclaimer: This code is licensed to you under the Apache
# License 2.0 (the "License"). You may not use this code except in compliance
# with the License. This code is not an official Juniper product. You can
# obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Third-Party Code: This code may depend on other components under separate
# copyright notice and license terms. Your use of the source code for those
# components is subject to the terms and conditions of the respective license
# as noted in the Third-Party source code file.
#

MY_DIR="$(dirname "$0")"
source "$MY_DIR/cmn.sh"

HTTP_SERVER_PORT=$(xmllint --xpath "//regressionConfig/regressionReportHTTPServerPort/text()" $REGRESSION_CONFIG_FILE)

is_running=`ps awxu | grep python | grep http_server.py | grep $HTTP_SERVER_PORT | wc -l`;

if [ $is_running -eq 1 ]; then
    log_debug "Python http server is running. Will restart it"
fi

pkill http_server.py
sleep 2
log_debug "Starting http server (port $HTTP_SERVER_PORT)..."
cd $REGRESSION_REPORT_DIR
$REGRESSION_SCRIPTS_DIR/http_server.py $HTTP_SERVER_PORT >> $REGRESSION_LOG_DIR/http_server.py.log 2>&1 < /dev/null &

exit 0
