#!/usr/bin/expect
#
# Advanced Forwarding Interface : AFI client examples
#
# Created by Sandesh Kumar Sodhi, January 2017
# Copyright (c) [2017] Juniper Networks, Inc. All rights reserved.
#
# All rights reserved.
#
# Notice and Disclaimer: This code is licensed to you under the Apache
# License 2.0 (the "License"). You may not use this code except in compliance
# with the License. This code is not an official Juniper product. You can
# obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Third-Party Code: This code may depend on other components under separate
# copyright notice and license terms. Your use of the source code for those
# components is subject to the terms and conditions of the respective license
# as noted in the Third-Party source code file.
#

source [file join [file dirname [info script]] lib.exp]
#
# Disable inline ICMP
#
log_debug "Will connect to VFP console and disable inline icmp"
set  script_name [file tail $argv0]

proc display_usage {} {
    global script_name
    puts "Usage  : $script_name"
    return 1
}

set spawn_id [login_vcp_ssh]

#
# timeout 1 minute
#
set timeout 60

expect "$vcp_prompt" { send "ls\r" }
expect "$vcp_prompt" { send "cprod -A fpc0 -c \"test jnh 0 icmp-inline-reply-disable\"\r" }
expect "$vcp_prompt" { send "cprod -A fpc0 -c \"debug jnh sandbox\"\r" }
expect "$vcp_prompt" { send "cprod -A fpc0 -c \"debug jnh sandbox hostpath\"\r" }
expect "$vcp_prompt" { send "cprod -A fpc0 -c \"show ukern_trace handles\" | grep JNH-SANDBOX\r" }
expect "$vcp_prompt" { send "cprod -A fpc0 -c \"show ukern_trace handles\" | grep JNH-SANDBOX | awk '{ print \$1 }'\r" }
expect "$vcp_prompt" { send "\r" }
log_debug "The output is '$expect_out(buffer)'."
set jnh_sandbox_ukern_trace_handle [lindex [split $expect_out(buffer) "\n"] end-1 ]
set jnh_sandbox_ukern_trace_handle [string trim $jnh_sandbox_ukern_trace_handle]
log_debug "jnh_sandbox_ukern_trace_handle: $jnh_sandbox_ukern_trace_handle hi"
expect "$vcp_prompt" { send "cprod -A fpc0 -c \"show ukern_trace $jnh_sandbox_ukern_trace_handle\"\r" }
expect "$vcp_prompt" { send "cprod -A fpc0 -c \"set ukern_trace $jnh_sandbox_ukern_trace_handle logging enable\"\r" }
expect "$vcp_prompt" { send "cprod -A fpc0 -c \"set ukern_trace $jnh_sandbox_ukern_trace_handle level extensive\"\r" }
expect "$vcp_prompt" { send "cprod -A fpc0 -c \"set ukern_trace $jnh_sandbox_ukern_trace_handle buffer 65536\"\r" }
expect "$vcp_prompt" { send "cprod -A fpc0 -c \"show ukern_trace handles\" | grep JNH-SANDBOX\r" }
expect "$vcp_prompt" { send "\r" }
send "exit\r"


close
exit 0
