#!/usr/bin/expect
#
# VMX setup scripts
#
# config_fwd_sandbox.exp
# This script connects to VCP via ssh and
# performs forwarding sandbox configuration
#
# Created by Sandesh Kumar Sodhi, January 2017
# Copyright (c) [2017] Juniper Networks, Inc. All rights reserved.
#
# All rights reserved.
#
# Notice and Disclaimer: This code is licensed to you under the Apache
# License 2.0 (the "License"). You may not use this code except in compliance
# with the License. This code is not an official Juniper product. You can
# obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Third-Party Code: This code may depend on other components under separate
# copyright notice and license terms. Your use of the source code for those
# components is subject to the terms and conditions of the respective license
# as noted in the Third-Party source code file.
#

source [file join [file dirname [info script]] lib.exp]

log_debug "Will connect to VCP via ssh and create forwarding sandbox"

set script_name [file tail $argv0]

proc display_usage {} {
    global script_name
    puts "Usage  : $script_name"
    return 1
}

set spawn_id [login_vcp_ssh]
#
# timeout 20 seconds
#
set timeout 20

expect "$vcp_prompt" { send "\r" }
expect "$vcp_prompt" { send "cli\r" }
log_debug "Expecting re_cli_prompt=$re_cli_prompt"
expect "$re_cli_prompt" { send "show version | no-more\r" }
expect "$re_cli_prompt" { send "edit\r" }
expect "$re_cli_config_prompt" { send "show | no-more\r" }
expect "$re_cli_config_prompt" { send "delete forwarding-options forwarding-sandbox jp4agent\r" }
expect "$re_cli_config_prompt" { send "commit\r" }
expect "$re_cli_config_prompt" { send "\r" }

set f [open "/root/JP4Agent/tools/docker/cfg/fwd_sandbox_junos_config.txt"]
set config_lines [split [read $f] "\n"]
close $f

foreach config_line $config_lines {
    set comment_char #
    if {[string match $comment_char* $config_line]} {
        log_debug "Ignoring $config_line"
    } else {
        expect "$re_cli_config_prompt" { send "$config_line\r" }
    }
}

expect "$re_cli_config_prompt" { send "show | compare | no-more\r" }
expect "$re_cli_config_prompt" { send "commit\r" }
expect "$re_cli_config_prompt" { send "exit\r" }
expect "$re_cli_prompt" { send "exit\r" }

close

#
# Regression scripts use this messagees to detect vmx setup status.
# If you change this message, please make the same change in regression scripts.
#
puts "Forwarding sandbox config: success!!"

exit 0
