#!/usr/bin/expect
#
# VMX setup scripts
#
# Created by Sandesh Kumar Sodhi, December 2017
# Copyright (c) [2017] Juniper Networks, Inc. All rights reserved.
#
# All rights reserved.
#
# Notice and Disclaimer: This code is licensed to you under the Apache
# License 2.0 (the "License"). You may not use this code except in compliance
# with the License. This code is not an official Juniper product. You can
# obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Third-Party Code: This code may depend on other components under separate
# copyright notice and license terms. Your use of the source code for those
# components is subject to the terms and conditions of the respective license
# as noted in the Third-Party source code file.
#

source /root/JP4Agent/tools/docker/scripts/lib.exp

#
# Disable flow cache
#
log_debug "Will connect to VFP console and disable flow cache"

set script_name [file tail $argv0]

proc display_usage {} {
    global script_name
    puts "Usage  : $script_name"
    return 1
}

set spawn_id [login_vfp_console]

#
# timeout 60 seconds
#
set timeout 60

expect "$vfp_prompt" { send "\r" }
expect "$vfp_prompt" { send "ifconfig ext REPLACE_WITH_VFP_IP netmask 255.255.0.0 up\r" }

send "exit\r"

close
exit 0
