# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import jp4cli_pb2 as jp4cli__pb2


class CmdHandlerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendCmd = channel.unary_unary(
        '/jp4cli.CmdHandler/SendCmd',
        request_serializer=jp4cli__pb2.CmdRequest.SerializeToString,
        response_deserializer=jp4cli__pb2.CmdReply.FromString,
        )


class CmdHandlerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SendCmd(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CmdHandlerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendCmd': grpc.unary_unary_rpc_method_handler(
          servicer.SendCmd,
          request_deserializer=jp4cli__pb2.CmdRequest.FromString,
          response_serializer=jp4cli__pb2.CmdReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'jp4cli.CmdHandler', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
