# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jp4cli.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='jp4cli.proto',
  package='jp4cli',
  syntax='proto3',
  serialized_pb=_b('\n\x0cjp4cli.proto\x12\x06jp4cli\"\x1c\n\nCmdRequest\x12\x0e\n\x06\x63mdstr\x18\x01 \x01(\t\"*\n\x08\x43mdReply\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0e\n\x06\x63mdout\x18\x02 \x01(\t2?\n\nCmdHandler\x12\x31\n\x07SendCmd\x12\x12.jp4cli.CmdRequest\x1a\x10.jp4cli.CmdReply\"\x00\x62\x06proto3')
)




_CMDREQUEST = _descriptor.Descriptor(
  name='CmdRequest',
  full_name='jp4cli.CmdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmdstr', full_name='jp4cli.CmdRequest.cmdstr', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=52,
)


_CMDREPLY = _descriptor.Descriptor(
  name='CmdReply',
  full_name='jp4cli.CmdReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='jp4cli.CmdReply.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cmdout', full_name='jp4cli.CmdReply.cmdout', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=96,
)

DESCRIPTOR.message_types_by_name['CmdRequest'] = _CMDREQUEST
DESCRIPTOR.message_types_by_name['CmdReply'] = _CMDREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CmdRequest = _reflection.GeneratedProtocolMessageType('CmdRequest', (_message.Message,), dict(
  DESCRIPTOR = _CMDREQUEST,
  __module__ = 'jp4cli_pb2'
  # @@protoc_insertion_point(class_scope:jp4cli.CmdRequest)
  ))
_sym_db.RegisterMessage(CmdRequest)

CmdReply = _reflection.GeneratedProtocolMessageType('CmdReply', (_message.Message,), dict(
  DESCRIPTOR = _CMDREPLY,
  __module__ = 'jp4cli_pb2'
  # @@protoc_insertion_point(class_scope:jp4cli.CmdReply)
  ))
_sym_db.RegisterMessage(CmdReply)



_CMDHANDLER = _descriptor.ServiceDescriptor(
  name='CmdHandler',
  full_name='jp4cli.CmdHandler',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=98,
  serialized_end=161,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendCmd',
    full_name='jp4cli.CmdHandler.SendCmd',
    index=0,
    containing_service=None,
    input_type=_CMDREQUEST,
    output_type=_CMDREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CMDHANDLER)

DESCRIPTOR.services_by_name['CmdHandler'] = _CMDHANDLER

# @@protoc_insertion_point(module_scope)
